### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by dguis** [dude2093350/xbox-live-emulator#3]
Mr. Ceo of cTech, you are receiving this message to ask for access to edit "xbox-live-emulator". Thanks!

-dguis CEO of D-Multi
![logo](https://user-images.githubusercontent.com/20483504/30244641-04021ff8-9577-11e7-882a-f3b025ab0bc3.jpg)

**Comment by dude2093350** [comment]
Hello dguis access is approved do you know python?

**Comment by dguis** [comment]
Thank you. No I do not know python but I can probably figure it out pretty easily. How did you learn it?

**Comment by dguis** [comment]
Excuse me. It doesn't appear I have been granted access. Did you go into settings > collaborators and add me? If so, I'll have to look at your end.
